#path to store dataset
data_path : "./data/"

#path to store output
output_path : "./output/"

#run identifier
run_id : "test_run"

#model training parameters
# device : "cuda"
device : "cpu"
classes : ['plane', 'car', 'bird', 'cat', 'deer', 'dog', 'frog', 'horse', 'ship', 'truck']
subset : Null
# subset : 100
train_batch_size : 128
test_batch_size : 128
data_augmentation : True
learning_rate : 0.1
epoch : 15
momentum : 0.9
weight_decay : 0
learning_rate_schedule : False

#model testing parameters
state_dict_path : "./output/test_run_state_dict.pth"